### ISSUE TITLE
Close Activity after onHide()

### ISSUE THREAD

**Issue by Informaticore** [Applifier/unity-ads#58]
Hey,

I tried to implement UnityAds and the few steps of the integration Guide for Android.
Something strange is happening.

I want to show the Ad after I finished a game. I call the show() methode, the video is playing everything is working. But now I want to close the current Activity when the Ad is finished, so I call finish() in the onHide() methode. This works exactly one time. If I go into this activity again do the same thing, my Activity is not finishing and I have no idea how this could happen.

Code:

in onCreate:
```java
        UnityAds.init(this, "54048", this);
        UnityAds.setDebugMode(BuildConfig.DEBUG);
        UnityAds.setTestMode(BuildConfig.DEBUG);
        UnityAds.changeActivity(this);
```
```java
    @Override
    public void onHide() {
        finish();
    }
```

I call UnityAds.changeActivity(this); in onResume as well like it was explained in the guide.
There is something strange with the Listener. Please help.

**Comment by gomsu** [comment]
Hello and thank you for your question. Looking at the issue it seems that every time you are showing ads you are calling "UnityAds.init()". This method is only meant to be called once during your application lifecycle (preferrably very early in the application startup). All the calls after the first init -method call are being ignored. 

Why the onHide() is not being called after the first time is because the init() method sets the listener for the UnityAds, but when you finish your first activity that listener you gave for UnityAds is also being destroyed. The next time your start the activity, the init -method call is being ignored by our SDK (it has already been initialized) and therefore also the new listener (the new activity you started) is not being set for our SDK.

To fix your problem, you only need to add one line after the changeActivity -call, which would be a call to UnityAds.setListener(this); this will set the UnityAds listener to the newly created activity. 

Also if you want to make your integration better, move the init, setDebugMode and setTestMode to very early startup of your application and also switch so that setDebugMode and setTestMode are being called before init.

**Comment by Informaticore** [comment]
Hey I figured it out. You should write this into the Integration Guide.
It would be ennought to call UnityAds.init() in the Application Class onCreate(). 

Sometimes an App has maybe just one Activity where it also shows the Ads.

**Comment by gomsu** [comment]
Yeah, That is another fix to actually listen to UnityAds in the activity that is only being destroyed when the application is being quit.

**Comment by Informaticore** [comment]
Seccond suggestion: there is no need for the Listener in the init methode then.
You can set it anytime you want to listen to.

**Comment by gomsu** [comment]
It's a good suggestion and we have considered it, though in many cases we have experienced that developers don't set it afterwards very often. We wanted to give as easy and fast integration as possible for those cases and therefore have left the listener also the the init method. The setListener() -method is basically for "advanced usage".

**Comment by Informaticore** [comment]
You could create a second show() methode with the lisrener. The listener makes not that much sens without showing an ad. expect the fetch callbacks. I am just interrested in onHide after showing the ad

**Comment by gomsu** [comment]
Hmm, not bad idea. Will take this into account when we are re-designing part of the UnityAds Native SDK API (iOS and Android that is). This will happen in about month or two. Our next big release will remove about 10% of the current SDK code and will fix a lot of inconsistency and the next release after that will most likely include some API changes. I will take this suggestion to the list that we will talk about when making the API changes. Thanks a lot! :)

**Comment by Informaticore** [comment]
No problem, I am glad that I could help.
We will see if this was worth it when my game is released ;-)

**Comment by gomsu** [comment]
I have now moved your idea to our system where we can find it when the time comes to rework our API. I'm closing this bug for now :). Thanks again for contacting!
